apiVersion: v1
kind: Service
metadata:
  name: weatherwebsite
  labels:
    app: vid
spec:
  ports:
    - port: 80
      name: weatherwebsite
      targetPort: weatherwebsite
  selector:
    app: vid
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherwebsite-deployment
  labels:
    app: vid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vid
  template:
    metadata:
      labels:
        app: vid
    spec:
      containers:
      - name: weatherwebsite
        image: 567935704451.dkr.ecr.us-east-1.amazonaws.com/inadev:latest
        ports:
        - containerPort: 5000
          name: weatherwebsite
